// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

type Querier interface {
	CreateCreator(ctx context.Context, arg CreateCreatorParams) (Creator, error)
	GetCreatorByEmail(ctx context.Context, email string) (GetCreatorByEmailRow, error)
}

var _ Querier = (*Queries)(nil)
