// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
)

type Querier interface {
	CreateCreator(ctx context.Context, arg CreateCreatorParams) (Creator, error)
	GetCreator(ctx context.Context, email string) (GetCreatorRow, error)
}

var _ Querier = (*Queries)(nil)
