// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"time"
)

type User struct {
	ID             int32
	FirstName      string
	LastName       string
	Email          string
	CreatedDate    time.Time
	Username       string
	PhoneNo        int32
	Gender         string
	ProfilePicture string
	Bio            string
}
